import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja" className="h-full">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-full flex flex-col`}
      >
        <div className="flex-1">
          {children}
        </div>
        <footer className="bg-indigo-950">
          <div className="w-full p-4 mx-auto text-sm text-center">
            <p>
              本サイトはファンコンテンツポリシーに基づき許可された非公式ファンコンテンツです。ウィザーズ社の承認や推薦を受けたものではありません。
            </p>
            <p>
              使用されている素材の一部はウィザーズ・オブ・ザ・コーストの所有物です。
              ©Wizards of the Coast LLC.
            </p>
          </div>
        </footer>
      </body>
    </html>
  );
}
